//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGoiMatHang
    {
        public string MaPhongDat { get; set; }
        public string MaHoaDonBan { get; set; }
        public string MaMatHang { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual tblHoaDonBan tblHoaDonBan { get; set; }
        public virtual tblMatHang tblMatHang { get; set; }
        public virtual tblPhongDat tblPhongDat { get; set; }
    }
}
