//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongDat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhongDat()
        {
            this.tblGoiDichVus = new HashSet<tblGoiDichVu>();
            this.tblGoiMatHangs = new HashSet<tblGoiMatHang>();
        }
    
        public string MaPhongDat { get; set; }
        public string MaPhong { get; set; }
        public string MaNhanVien { get; set; }
        public string MaKhachHang { get; set; }
        public Nullable<System.DateTime> ThoiGianPhongDat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoiDichVu> tblGoiDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblGoiMatHang> tblGoiMatHangs { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblPhongHat tblPhongHat { get; set; }
    }
}
