//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPhongHat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPhongHat()
        {
            this.tblPhongDats = new HashSet<tblPhongDat>();
        }
    
        public string MaPhongHat { get; set; }
        public string TenPhongHat { get; set; }
        public Nullable<int> TrangThaiPhong { get; set; }
        public string MaLoaiPhong { get; set; }
        public Nullable<int> TrangThaiXoa { get; set; }
    
        public virtual tblLoaiPhong tblLoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPhongDat> tblPhongDats { get; set; }
    }
}
